### ISSUE TITLE
带有 provider 字段时无法启动

### ISSUE THREAD

**Issue by txyyh** [qjebbs/sing-box#11]
### Operating system

Windows

### System version

Windows 11 Enterprise 22H2

### Installation type

Original sing-box Command Line

### Version

<details>
console output: 
sing-box version unknown

Environment: go1.21.1 windows/amd64
Tags: with_gvisor,with_quic,with_clash_api,with_ech,with_utls,with_dhcp
Revision: e888176aadc0bedfb2c629b42669ec72a9d941d0
CGO: enabled

GitHub Action: https://github.com/txyyh/sing-box-build/actions/runs/6217173644
</details>

### Description

配置文件带有 provider 有关配置时无法启动，去掉则可以正常启动

### Reproduction

1. 编写一份带有 provider 字段的 config.json
2. 使用该配置文件启动
3. 程序报错

### Logs

<details>
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/sagernet/sing-box/outbound.(*Selector).Start(0xc0002140e0)
        github.com/sagernet/sing-box/outbound/selector.go:78 +0x3c5
github.com/sagernet/sing-box.(*Box).startOutbounds(0xc000162d10)
        github.com/sagernet/sing-box/box_outbound.go:47 +0x671
github.com/sagernet/sing-box.(*Box).preStart(0xc000162d10)
        github.com/sagernet/sing-box/box.go:262 +0x457
github.com/sagernet/sing-box.(*Box).start(0xc000162d10)
        github.com/sagernet/sing-box/box.go:270 +0x2a
github.com/sagernet/sing-box.(*Box).Start(0xc000162d10)
        github.com/sagernet/sing-box/box.go:222 +0x36
main.create()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:178 +0x425
main.run()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:191 +0x10d
main.glob..func7(0xc00019d300?, {0x169ffce?, 0x4?, 0x169ffd2?})
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:30 +0x17
github.com/spf13/cobra.(*Command).execute(0x2151e40, {0x21b32a0, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x21529c0)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        github.com/sagernet/sing-box/cmd/sing-box/main.go:36 +0x1e

or

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x1222ed9]

goroutine 5 [running]:
github.com/sagernet/sing-box/outbound.(*Selector).DialContext(0x15bde6bbec8?, {0x187b0e0?, 0xc00009e000?}, {0x169fa1c?, 0xc000269990?}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc0000381e0, ...}})
        github.com/sagernet/sing-box/outbound/selector.go:104 +0x39
github.com/sagernet/sing-box/provider.(*Remote).download.func1({0x187b0e0, 0xc00009e000}, {0x169fa1c, 0x3}, {0xc0000381e0?, 0x96b591?})
        github.com/sagernet/sing-box/provider/remote.go:405 +0xd6
net/http.(*Transport).dial(0xc000269c40?, {0x187b0e0?, 0xc00009e000?}, {0x169fa1c?, 0xc000269a90?}, {0xc0000381e0?, 0x215ae00?})
        net/http/transport.go:1183 +0xd2
net/http.(*Transport).dialConn(0xc000098000, {0x187b0e0, 0xc00009e000}, {{}, 0x0, {0xc0001b4230, 0x5}, {0xc0000381e0, 0x1f}, 0x0})
        net/http/transport.go:1625 +0x7e8
net/http.(*Transport).dialConnFor(0x10b90c5?, 0xc0000a2000)
        net/http/transport.go:1467 +0x9f
created by net/http.(*Transport).queueForDial in goroutine 25
        net/http/transport.go:1436 +0x3cb
</details>

**Comment by qjebbs** [comment]
try f5e7a88d79b64b5800def67acc3a1373b4c7a74d
