### ISSUE TITLE
请教一下singbox的链式代理应该怎么设置

### ISSUE THREAD

**Issue by donnanszex7654** [qjebbs/sing-box#14]
你好，我想请教一下singbox的链式代理要怎么设置？我google了很多，都没有很明白的讲清楚要怎么设置，在singbox下的提问中看到了你的提问，可以麻烦请教一下在客户端中要怎么设置配置文件实现链式代理吗？我想实现的功能是套一层warp。

**Comment by qjebbs** [comment]
https://sing-box.sagernet.org/configuration/shared/dial/#detour

`A.detour="B"` makes `A-->B`
