### ISSUE TITLE
可以增加在outbounds下使用节点过滤字段的功能吗

### ISSUE THREAD

**Issue by cw2023** [qjebbs/sing-box#2]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

![屏幕截图 2023-05-25 170730](https://github.com/qjebbs/sing-box/assets/122753782/e1310fbb-6f9e-48d4-aff6-ec6fb258bea9)
如图所示

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by qjebbs** [comment]
How about this?

```jsonc
{
  "providers": [
    {
      "tag": "CLM 香港",
      "url": "...",
      "include": "香港"
    },
    {
      "tag": "CLM 日本",
      "url": "...",
      "include": "日本"
    }
  ],
  "outbounds": [
    {
      "tag": "香港",
      "type": "selector",
      "providers":[
        "CLM 香港"
      ]
    },{
      "tag": "日本",
      "type": "selector",
      "providers":[
        "CLM 日本"
      ]
    }
  ]
}
```

**Comment by cw2023** [comment]
说实话我在之前就是这么用的，虽然可以实现相同的效果，但整个配置文件就会变的复杂，读取效率变低，比如我有三个订阅源，每个订阅源进行5种地区分类，那么providers每次启动或者更新订阅时就需要15次url请求，其实12次都是重复的，程序启动速度就会变慢。当然如果providers可以读取本地文件也可以，就只需3次url请求。还有就是建议在providers里加入“健康检查”字段，这样即使outbounds下全是selector或者部分是selector，所有节点也会定期检查，这就类似clash的providers了。
