### ISSUE TITLE
正则匹配错误

### ISSUE THREAD

**Issue by woshishiq1** [qjebbs/sing-box#3]
尝试了下exclude正则："exclude": "^(?!.*(?:https://t.me/qidian_yun|卐奇点㊣|卐奇点卐)).*",报错：[31mFATAL [0m[0000] parse provider[1]: error parsing regexp: invalid or unsupported Perl syntax: (?!

使用内核https://github.com/CHIZI-0618/sing-box/suites/13078823103/artifacts/709606981

**Comment by qjebbs** [comment]
go `regexp` doesn't support the syntax, nothing I can do here.
