### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by woshishiq1** [qjebbs/sing-box#5]
unsupported transport tcp | part error: {"v":"2","ps":"剩余流量：94.88% 86.71GB","add":"www.g00gle.com","port":"10086","id":"2661b","aid":"2","net":"tcp","type":"none","host":"","tls":""} | invalid port: strconv.ParseUint: parsing "\"剩余流量：94.88% 86.71GB\",\"add\":\"www.g00gle.com\",\"port\":\"10086\",\"id\":\"26614a5-9371-a44313a75b6b\",\"aid\":\"2\",\"net\":\"tcp\",\"type\":\"none\",\"host\":\"\",\"tls\":\"\"}": invalid syntax 订阅成功没有节点

**Comment by woshishiq1** [comment]
ERROR provider[provider1]: unsupported transport tcp | part error: {"v":"2","ps":"剩余流量：94.88% 86.71GB","add":"www.g00gle.com","port":"10086","id":"2661b","aid":"2","net":"tcp","type":"none","host":"","tls":""} | invalid port: strconv.ParseUint: parsing "\"剩余流量：94.88% 86.71GB\",\"add\":\"www.g00gle.com\",\"port\":\"10086\",\"id\":\"26614a5-9371-a44313a75b6b\",\"aid\":\"2\",\"net\":\"tcp\",\"type\":\"none\",\"host\":\"\",\"tls\":\"\"}": invalid syntax

**Comment by woshishiq1** [comment]
用这个https://t.me/e58695/146 里面同样是你的内核 没有这个问题

**Comment by qjebbs** [comment]
已将错误信息优化为：

```
 [V2RayNG] unsupported transport tcp | [Quantumult] bad format | [ShadowRocket] bad format
```

关键信息是`unsupported transport tcp`，文档如下：

<https://sing-box.sagernet.org/zh/configuration/shared/v2ray-transport/>
```
与 v2ray-core 的区别
没有 TCP 传输层, 纯 HTTP 已合并到 HTTP 传输层。
没有 mKCP 传输层。
没有 DomainSocket 传输层。
```

解析成功的链接还是能生效的，应不影响使用。你也可以使用 `"exclude": "剩余流量"`，把这个节点过滤掉。
